//! Simulation constants

pub const PROJECT_TITLE: &str = "Last Ditch";

pub const TESTING: bool = true;

pub const SQRT_2: f32 = std::f32::consts::SQRT_2;
pub const SQRT_3: f32 = 1.7320508;

pub const CELL_RADIUS_IN_METERS: f32 = 0.5;
pub const CELL_SIZE_IN_METERS: f32 = 2.0 * CELL_RADIUS_IN_METERS;
pub const CELL_AREA_IN_METERS: f32 = CELL_SIZE_IN_METERS * CELL_SIZE_IN_METERS;
pub const CELL_VOLUME_IN_METERS: f32 =
    CELL_SIZE_IN_METERS * CELL_SIZE_IN_METERS * CELL_SIZE_IN_METERS;

pub const SECTOR_RADIUS_IN_CELLS: usize = 8;
pub const SECTOR_SIZE_IN_CELLS: usize = 2 * SECTOR_RADIUS_IN_CELLS + 1;
pub const SECTOR_AREA_IN_CELLS: usize = SECTOR_SIZE_IN_CELLS * SECTOR_SIZE_IN_CELLS;
pub const SECTOR_VOLUME_IN_CELLS: usize =
    SECTOR_SIZE_IN_CELLS * SECTOR_SIZE_IN_CELLS * SECTOR_SIZE_IN_CELLS;

pub const SECTOR_RADIUS_IN_METERS: f32 =
    CELL_SIZE_IN_METERS * SECTOR_RADIUS_IN_CELLS as f32 + CELL_RADIUS_IN_METERS;
pub const SECTOR_SIZE_IN_METERS: f32 = 2.0 * SECTOR_RADIUS_IN_METERS;
pub const SECTOR_AREA_IN_METERS: f32 = SECTOR_SIZE_IN_METERS * SECTOR_SIZE_IN_METERS;
pub const SECTOR_VOLUME_IN_METERS: f32 =
    SECTOR_SIZE_IN_METERS * SECTOR_SIZE_IN_METERS * SECTOR_SIZE_IN_METERS;

pub const WORLD_RADIUS_IN_SECTORS: usize = 2;
pub const WORLD_SIZE_IN_SECTORS: usize = 2 * WORLD_RADIUS_IN_SECTORS + 1;
pub const WORLD_AREA_IN_SECTORS: usize = WORLD_SIZE_IN_SECTORS * WORLD_SIZE_IN_SECTORS;
pub const WORLD_VOLUME_IN_SECTORS: usize =
    WORLD_SIZE_IN_SECTORS * WORLD_SIZE_IN_SECTORS * WORLD_SIZE_IN_SECTORS;

pub const WORLD_RADIUS_IN_CELLS: usize =
    SECTOR_SIZE_IN_CELLS * WORLD_RADIUS_IN_SECTORS + SECTOR_RADIUS_IN_CELLS;
pub const WORLD_SIZE_IN_CELLS: usize = 2 * WORLD_RADIUS_IN_CELLS + 1;
pub const WORLD_AREA_IN_CELLS: usize = WORLD_SIZE_IN_CELLS * WORLD_SIZE_IN_CELLS;
pub const WORLD_VOLUME_IN_CELLS: usize =
    WORLD_SIZE_IN_CELLS * WORLD_SIZE_IN_CELLS * WORLD_SIZE_IN_CELLS;

pub const WORLD_RADIUS_IN_METERS: f32 =
    CELL_SIZE_IN_METERS * WORLD_RADIUS_IN_CELLS as f32 + CELL_RADIUS_IN_METERS;
pub const WORLD_SIZE_IN_METERS: f32 = 2.0 * WORLD_RADIUS_IN_METERS;
pub const WORLD_AREA_IN_METERS: f32 = WORLD_SIZE_IN_METERS * WORLD_SIZE_IN_METERS;
pub const WORLD_VOLUME_IN_METERS: f32 =
    WORLD_SIZE_IN_METERS * WORLD_SIZE_IN_METERS * WORLD_SIZE_IN_METERS;

pub const SIMULATION_TICK_FREQUENCY: u64 = 20;
pub const SIMULATION_MAX_TICKS_PER_FRAME: u32 = 5;
pub const SIMULATION_TICK_DURATION: std::time::Duration =
    std::time::Duration::from_nanos(1_000_000_000 / SIMULATION_TICK_FREQUENCY);
pub const SIMULATION_TICK_IN_SECONDS: f32 = SIMULATION_TICK_DURATION.as_secs_f32();
pub const SIMULATION_TICK_IN_SECONDS_SQUARED: f32 =
    SIMULATION_TICK_IN_SECONDS * SIMULATION_TICK_IN_SECONDS;
pub const SIMULATION_ENTITY_MAX: usize = 500;

pub const MOVEMENT_COST_STRAIGHT: u32 = 100;
pub const MOVEMENT_COST_DIAGONAL: u32 = 141;
pub const MOVEMENT_COST_CORNER: u32 = 173;

pub const GRAVITY_ACCELERATION: f32 = 60.0;
pub const EPSILON_COLLISION: f32 = 0.001;
pub const MAX_RESOLVE_ITERATIONS: usize = 40;
pub const MAXIMUM_CLEARANCE: u32 = 5;
pub const MINIMUM_CLEARANCE: u32 = 3;
pub const CONTACT_OFFSET: f32 = 0.001;
pub const MINIMUM_APPROACH_DISTANCE: f32 = f32::EPSILON * f32::EPSILON;

pub const JUDGE_DEFAULT_SPEED: f32 = 8.0;
pub const JUDGE_DEFAULT_JUMP_SPEED: f32 = 16.0;

pub const JUDGE_DEFAULT_SIZE_X: f32 = 0.6;
pub const JUDGE_DEFAULT_SIZE_Y: f32 = 0.6;
pub const JUDGE_DEFAULT_SIZE_Z: f32 = 1.9;

pub const PITCH_LIMIT: f32 = 89.99;

pub const INITIAL_NATION_POPULATION: i32 = 16;

pub const PERSON_DEFAULT_SPEED: f32 = 6.0;
pub const PERSON_DEFAULT_JUMP_SPEED: f32 = 8.0;

pub const PERSON_DEFAULT_SIZE_X: f32 = 0.6;
pub const PERSON_DEFAULT_SIZE_Y: f32 = 0.6;
pub const PERSON_DEFAULT_SIZE_Z: f32 = 1.6;

pub const FLOOR_HEIGHT: usize = 8;
pub const LOWER_FLOOR_COUNT: usize = 4;
pub const BUILDING_RADIUS: usize = WORLD_RADIUS_IN_CELLS - SECTOR_SIZE_IN_CELLS;

pub const CENTRAL_ELEVATOR_SHAFT_RADIUS: usize = 3;
pub const EXTERNAL_HALL_SIZE: usize = 3;
pub const ROOM_SIZE_MIN: usize = 3;
