#include "RenderConstants.h"

#include "MapConstants.h"

const I32 SCREEN_SIZE_X{1024};
const I32 SCREEN_SIZE_Y{768};
const I32 HALF_SCREEN_SIZE_X{SCREEN_SIZE_X / 2};
const I32 HALF_SCREEN_SIZE_Y{SCREEN_SIZE_Y / 2};
const I32 VIEW_X{HALF_SCREEN_SIZE_X / TILE_SIZE + 1};
const I32 VIEW_Y{HALF_SCREEN_SIZE_Y / TILE_SIZE + 1};

const F32 ASPECT_RATIO{(F32)(SCREEN_SIZE_X / SCREEN_SIZE_Y)};
