#[derive(Copy, Clone, Debug, Hash, Eq, PartialEq, PartialOrd, Ord)]
pub enum Kind {
    Empty,
    Engraved1,
    Engraved2,
    Stone1,
    Stone2,
    Polished1,
    Polished2,
    MagentaStone,
    PurpleStone,
    TealStone,
    CrimsonStone,
    Icon1,
    Icon2,
    Icon3,
    Icon4,
    North,
    West,
    South,
    East,
}
